name: muninn_iha_v2
description: "ODİN – Tactical Aerial Intelligence Controller"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  # MAVLink protokolü
  dart_mavlink: ^0.1.0

  # Konum
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Kalıcı ayarlar
  shared_preferences: ^2.5.4

  # İkon seti
  cupertino_icons: ^1.0.8
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon.png